// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Dk1vdnvgAQRJjbEYq6ezoS8_WI5mHhM',
    appId: '1:655505759467:web:e190e17652984d6007b2ae',
    messagingSenderId: '655505759467',
    projectId: 'orm-firebase',
    authDomain: 'orm-firebase.firebaseapp.com',
    storageBucket: 'orm-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ4yPnMBuOOsFkRo2fqFCUzHu2yZYxPnc',
    appId: '1:655505759467:android:94bf5e3746aea74707b2ae',
    messagingSenderId: '655505759467',
    projectId: 'orm-firebase',
    storageBucket: 'orm-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBLTf5R6IHiZjDwt3WOyxdk5fHYVE6ja4',
    appId: '1:655505759467:ios:f2d2f6a7f450fd8107b2ae',
    messagingSenderId: '655505759467',
    projectId: 'orm-firebase',
    storageBucket: 'orm-firebase.appspot.com',
    iosBundleId: 'com.example.firebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBLTf5R6IHiZjDwt3WOyxdk5fHYVE6ja4',
    appId: '1:655505759467:ios:215b720cf9a6b86507b2ae',
    messagingSenderId: '655505759467',
    projectId: 'orm-firebase',
    storageBucket: 'orm-firebase.appspot.com',
    iosBundleId: 'com.example.firebaseExample.RunnerTests',
  );
}
